"""Source-grounded candidate extraction. This script never grants human approval."""
import json
import re
import shutil
from datetime import date
from jsonschema import validate
from .store import ROOT,COUNTRIES,connect,write_json,now,digest,finding_version

# Source index is captured by collect-sources and extend-us. The stable specification
# below resolves by URL suffix, never by nondeterministic download order.
# country, URL substring, title, class, publication, decision, effective, status, claim, passage anchor
SPECS=[
('SE','nationell-strategi-mot-ensamhet-overlamnas','A national strategy against loneliness','strategy','2025-02-28',None,None,'published','Sweden’s Public Health Agency presented its first national strategy against loneliness on 28 February 2025, including access to social settings and reducing barriers to participation.','Folkhälsomyndigheten presenterade i dag Sveriges första strategi'),
('SE','uppdrag-till-livsmedelsverket-om-att-sprida','Nutrition knowledge for older people','policy','2024-05-16',None,None,'announced','The Swedish government assigned the Food Agency to compile and share knowledge about food and meals for older people, including material for eldercare staff and decision makers.','Livsmedelsverket har därför fått i uppdrag'),
('SE','kartlaggning-av-aldres-psykiska-halsa','Mapping older people’s mental health','policy','2024-03-27',None,None,'announced','The Swedish government commissioned the Public Health Agency to map older people’s mental health, incorporating their own accounts of their living circumstances.','Regeringen ger Folkhälsomyndigheten i uppdrag'),
('SE','varje-dag-raknas-nationell-demensstrategi','Dementia strategy 2025–2028','strategy','2025-01-23',None,None,'adopted','Sweden published its adopted national dementia strategy for 2025–2028, covering development of care and support for people living with dementia.','Regeringen har därför beslutat om en utvecklad nationell demensstrategi'),
('SE','ministern-besoker-sydkorea-och-japan','Ministerial exchange on ageing','political statement','2024-09-30',None,None,'announced','Sweden announced minister Anna Tenje’s visit to South Korea and Japan to discuss demographic change, eldercare and healthy ageing. This records a stated diplomatic agenda, not a new law.','Den 30 september till den 4 oktober besöker'),
('SE','ny-lag-om-tobak-och-liknande-produkter_h601sou3','Smoke-free public spaces','legislation','2018-12-12','2018-12-12','2019-07-01','adopted','The Swedish parliament approved new tobacco rules extending smoke-free restrictions to certain outdoor public places. Most provisions began on 1 July 2019; tracking and security marking had a separate start date.','De nya reglerna börjar gälla den 1 juli 2019.'),
('SE','en-fast-omsorgskontakt-i-hemtjansten_h901sou24','A designated contact in home care','legislation','2022-05-04','2022-05-04','2022-07-01','adopted','Sweden’s parliament approved a requirement to offer home-care recipients a designated care contact unless clearly unnecessary, starting 1 July 2022. The professional-title requirement had a later start date.','Kravet på att erbjuda en fast omsorgskontakt börjar gälla'),
('SE','uppdrag-att-betala-ut-statsbidrag-till-kommunerna','SEK 143.5m for health conversations','funding','2023-02-20',None,None,'allocated','The Swedish government instructed the National Board of Health and Welfare to distribute SEK 143.5 million to municipalities for health conversations intended to counter loneliness among older people.','Regeringen uppdrar åt Socialstyrelsen att betala ut 143,5 miljoner'),
('SE','prop.-201718249','A proposal for more equal health','strategy','2018-04-20',None,None,'proposed','Sweden’s government proposed a public-health framework addressing avoidable health inequalities within a generation. This source establishes the proposal and its goals, not parliamentary adoption.','Regeringen uppmanar alla att aktivt arbeta'),
('SE','new-research-for-more-sustainable','Nordic eldercare research awards','funding','2025-06-05',None,None,'awarded','Forte reported five funded projects in a NordForsk call on sustainable health and social care for older people. Forte was one of several funders; the awards span Nordic and Baltic countries.','Five projects have now been granted funding'),
('SE','starkta-insatser-for-aldre-och-for-de-som-vardar','Proposed support for older people and carers','legislation','2025-11-20',None,None,'proposed','Sweden’s government proposed designated contacts in residential eldercare and stronger support for family carers in bill 2025/26:60. The bill proposed 1 July 2026 commencement; this document alone does not establish enactment.','Lagändringarna föreslås träda i kraft den 1 juli 2026.'),
('SE','nya-rekommendationer-sa-kan-verksamheter','Guidance on mental health after 65','policy','2026-09-01',None,None,'published','Sweden’s Public Health Agency published recommendations for organisations working with people aged 65 and over, including involving older people in decisions and enabling meaningful daily activities.','De vänder sig till olika verksamheter som möter äldre personer'),
('US','/tobacco-21','Federal tobacco sales age 21','legislation','2025-08-07','2019-12-20','2019-12-20','enacted','The United States raised the federal minimum age for tobacco sales from 18 to 21 through legislation signed on 20 December 2019, effective immediately. FDA’s current summary also covers e-cigarettes.','On Dec. 20, 2019, the President signed legislation'),
('US','fda-issues-final-rule-increasing','Photo identification for tobacco sales','legislation','2024-08-29',None,'2024-09-30','final_rule','FDA issued a final rule requiring retailers to check photo identification for tobacco purchasers under 30, replacing the under-27 threshold, from 30 September 2024.','Beginning Sept. 30, retailers must verify with photo identification'),
('US','healthy-people-2030-here','Healthy People 2030','strategy','2020-08','2020-08-18',None,'launched','ODPHP launched Healthy People 2030 on 18 August 2020, setting national public-health objectives and targets, with greater emphasis on social determinants of health and health literacy.','On August 18, ODPHP released'),
('US','2024-budget-and-paylines-update','NIA fiscal-year 2024 funding','funding','2024-03',None,None,'allocated','NIA reported that the 2024 appropriations law allocated more than US$4.5 billion to the institute and added US$100 million for Alzheimer’s and related dementia research across NIA and NINDS.','The law sets the total NIA budget allocation'),
('US','looking-forward-nihs-alzheimers','A proposed dementia research budget','funding','2022-07-27',None,None,'proposed','NIH’s professional-judgment proposal estimated a need for US$3.87 billion for Alzheimer’s and related dementia research in fiscal year 2024, including US$321 million in additional resources. This was a proposal, not an appropriation.','For FY 2024, NIH estimates $321 million'),
('US','final-reconsideration-national-ambient','A tighter annual PM2.5 standard','legislation','2024-02-07','2024-02-07',None,'final_rule','EPA announced a final annual primary PM2.5 standard of 9.0 micrograms per cubic metre on 7 February 2024. This historical rule record does not establish its current litigation or implementation status.','standard at 9.0 micrograms per cubic meter'),
('US','hhs-delivers-first-national-strategy','A national strategy for family carers','strategy','2022',None,None,'published','HHS released its 2022 National Strategy to Support Family Caregivers, identifying nearly 350 federal actions and more than 150 actions for other levels of government and the private sector.','It highlights nearly 350 actions the federal government'),
('US','final-policies-medicare-diabetes-prevention','A one-year Medicare prevention programme','policy','2021-11-02',None,'2022-01-01','final_rule','CMS finalised a shorter, one-year Medicare Diabetes Prevention Program for participants starting on or after 1 January 2022, removing the second-year ongoing-maintenance phase.','CMS has finalized the proposal to shorten the MDPP services period'),
('US','proposed-policies-medicare-diabetes-prevention','Proposed expansion of Medicare prevention','policy','2017-07-13',None,None,'proposed','CMS proposed implementation policies for the expanded Medicare Diabetes Prevention Program, including a proposed 1 April 2018 service start. This fact sheet describes proposals open for comment.','We propose to revise our policy to state that MDPP services'),
('US','hhs-backs-ai-innovation','US$2m caregiver technology competition','funding','2025-11-18',None,None,'announced','HHS announced a US$2 million Caregiver Artificial Intelligence Prize Competition to support caregivers of older adults and people with disabilities. This is an announced competition, not evidence of awards or health benefits.','today announced a new $2 million Caregiver Artificial Intelligence Prize Competition'),
('SG','white-paper-on-healthier-sg','Healthier SG white paper','strategy','2022-09-21','2022-09-21',None,'submitted','Singapore’s Ministry of Health submitted the Healthier SG white paper to Parliament, proposing a shift toward preventive care and lasting relationships with family doctors. Submission is distinct from subsequent implementation.','The White Paper on Healthier SG has been submitted to Parliament'),
('SG','opening-speech-by-mr-ong-ye-kung-minister-for-health-at-the-healthier','The minister’s case for prevention','political statement','2022-10-04',None,None,'statement','Health minister Ong Ye Kung asked Parliament to endorse the Healthier SG white paper as the basis for a prevention-focused health system. The speech records the minister’s position, not a measured health outcome.','That this House endorses Paper Cmd. 19 of 2022'),
('SG','healthier-sg-enrolment-programme','Healthier SG enrolment opens','policy','2023-07-02',None,'2023-07-05','announced','Singapore announced Healthier SG enrolment from 5 July 2023, initially inviting citizens and permanent residents aged 60 and over to enrol with participating GP clinics or polyclinics.','From 5 July 2023, Singapore Citizens and Permanent Residents'),
('SG','launch-of-the-2023-action-plan-for-successful-ageing','The 2023 plan for successful ageing','strategy','2023-01-30','2023-01-30',None,'launched','Singapore launched its 2023 Action Plan for Successful Ageing, organised around care, contribution and connectedness, with community initiatives responding to the needs of current and future seniors.','The Ministerial Committee on Ageing (MCA) has launched'),
('SG','enhancing-preventive-health-and-aged-care','S$3.5bn for Age Well SG','funding','2024-03-06',None,None,'announced','Singapore announced S$3.5 billion over the next decade for Age Well SG, including S$1.9 billion for Ministry of Health initiatives to support ageing in the community.','Over the next decade, the government will dedicate $3.5 billion'),
('SG','good-progress-in-the-implementation-of-age-well','S$140m for active ageing centres','funding','2024-10-12',None,None,'announced','Singapore’s Ministry of Health announced S$140 million to enhance and expand Active Ageing Centres as part of Age Well SG. This records planned spending, not measured outcomes.','will dedicate $140 million to enhance and expand'),
('SG','minimum-legal-age-for-tobacco-raised-to-21','Tobacco minimum age reaches 21','legislation','2020-12-30','2017-11-07','2021-01-01','adopted','Singapore announced the final step of its legislated increase in the minimum age for tobacco purchase, use, possession, sale and supply, from 20 to 21 on 1 January 2021.','From 1 January 2021, the Minimum Legal Age'),
('SG','mandatory-nutrition-labelling-and-advertising','Nutri-Grade for packaged beverages','legislation','2021-12-30','2021-12-30','2022-12-30','regulations_published','Singapore published regulations introducing Nutri-Grade labelling and advertising restrictions for prepacked beverages and automatic dispensers, with requirements starting on 30 December 2022.','From 30 December 2022, “Nutri-Grade” beverages sold'),
('SG','extension-of-nutri-grade-requirements','Nutri-Grade for freshly prepared drinks','legislation','2023-06-30','2023-06-30','2023-12-30','regulations_published','Singapore published regulations extending Nutri-Grade labelling and advertising restrictions to freshly prepared beverages in specified settings, effective 30 December 2023.','From 30 December 2023, the Nutri-Grade labelling requirements'),
('SG','diabetes-the-war-continues','War on Diabetes','strategy','2017-08-22','2016-04',None,'reported_launch','Singapore’s Ministry of Health reported that it had launched the War on Diabetes in April 2016 as a national effort to address diabetes and support healthier ageing. The retrospective source was published in August 2017.','In April 2016, MOH declared War on Diabetes'),
('SG','public-consultation-on-measures-to-reduce-sugar','Consultation on sugary drinks','policy','2018-12-04',None,'2018-12-04','consultation','Singapore’s Ministry of Health and Health Promotion Board opened a consultation on measures to reduce sugar from prepackaged sweetened beverages, running from 4 December 2018 to 25 January 2019.','The public consultation will be held from 4 December 2018'),
('SG','moh-launches-report-on-progress-made','Reporting on diabetes prevention','policy','2019-11-17',None,None,'published','Singapore’s Ministry of Health released a progress report on the War on Diabetes, organising its account around prevention, early detection and intervention, and disease management. Reported progress is not an independently estimated policy effect.','The Ministry of Health (MOH) has released a summary report'),
]

def normal(s):return re.sub(r'\s+',' ',s).strip()

def main():
    index=json.loads((ROOT/'data/source-index.json').read_text())
    schema=json.loads((ROOT/'schema/finding.schema.json').read_text())
    grouped={c:[] for c in COUNTRIES};provenance={c:{} for c in COUNTRIES}
    for country,suffix,title,classification,pub,decision,effective,status,claim,anchor in SPECS:
        matches=[r for r in index if suffix.lower() in r['url'].lower() and r['status']=='retrieved']
        if len(matches)!=1:raise ValueError(f'Ambiguous/missing source: {suffix}: {len(matches)}')
        source=matches[0]['source'];text=normal((ROOT/source['text_path']).read_text());needle=normal(anchor)
        if needle not in text:raise ValueError('Unsupported passage: '+anchor)
        start=text.index(needle);excerpt=' '.join(text[start:].split()[:min(22,len(needle.split())+3)])
        fid=f'{country.lower()}-{101+len(grouped[country]):03d}'
        date_note='Source date is publication or the explicitly dated decision; unknown dates remain unset.'
        if status=='proposed':date_note+=' A proposed start date is not an enacted effective date.'
        if len(pub)<10:date_note+=' Publication precision is limited to the stated year/month; no day is inferred.'
        if decision and decision!=pub:date_note+=' Decision/launch date differs from the source publication date.'
        if country=='US' and '/tobacco-21' in suffix:date_note+=' Publication field is the FDA page’s current-as-of date, not the 2019 law date.'
        if country=='SE' and 'h601sou3' in suffix:date_note+=' Tracking/security-marking provisions started 20 May 2019.'
        if country=='SE' and 'h901sou24' in suffix:date_note+=' The assistant-nurse title requirement started 1 July 2023.'
        f={'id':fid,'type':'finding','country':country,'classification':classification,'claim':claim,'source_url':source['canonical_url'],'source_date':pub,'confidence':'medium' if source.get('retrieval_method') or len(pub)<10 else 'high','retrieved_at':source['retrieved_at'],'source_note':date_note}
        validate(f,schema)
        prov={'title':title,'source_id':source['id'],'publisher':source['publisher'],'source_title':source['title'],'canonical_url':source['canonical_url'],'retrieved_at':source['retrieved_at'],'content_hash':source['content_hash'],'retrieval_method':source.get('retrieval_method','direct_https'),'hash_basis':source.get('hash_basis','original response bytes'),'publication_date':pub,'decision_date':decision,'effective_date':effective,'status':status,'date_note':date_note,'supporting_passage':excerpt,'passage_location':f'Normalised extracted text, character {start}; search for the quoted passage.','relevance':'National prevention or ageing-related policy context. No lifespan effect is inferred.','classification_rationale':{'legislation':'A bill, adopted legislative decision or regulatory instrument; status distinguishes its stage.','policy':'An administrative action, programme or consultation.','strategy':'A stated national framework or coordinated programme.','funding':'A budget proposal, allocation or funding announcement; status distinguishes commitments and awards.','political statement':'An attributed ministerial position or announced agenda.'}[classification],'contradictions':[],'review_status':'pending'}
        version=finding_version(f,prov)
        with connect() as db:
            db.execute('INSERT OR REPLACE INTO policy_events VALUES(?,?,?,?,?,?,?,?,?,?,?)',(fid,country,source['id'],status,pub,decision,effective,date_note,prov['relevance'],excerpt,prov['passage_location']))
            db.execute('INSERT INTO findings VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,version_hash=excluded.version_hash',(fid,fid,country,classification,json.dumps(f,ensure_ascii=False),version,now()))
        grouped[country].append(f);provenance[country][fid]=prov
    legacy=ROOT/'eval/legacy/sweden.seed.json'
    if not legacy.exists():legacy.parent.mkdir(parents=True,exist_ok=True);shutil.copy(ROOT/'eval/findings/sweden.json',legacy)
    manifest={}
    for c,(slug,_,_) in COUNTRIES.items():
        write_json(ROOT/f'eval/findings/{slug}.json',grouped[c]);write_json(ROOT/f'eval/provenance/{slug}.json',provenance[c])
        vp=ROOT/f'eval/verdicts/{slug}.verdicts.json'
        if not vp.exists():write_json(vp,{})
        for f in grouped[c]:manifest[f['id']]=finding_version(f,provenance[c][f['id']])
    benchmark=ROOT/'eval/benchmark.json'
    if not benchmark.exists():write_json(benchmark,{'created_at':now(),'target_accuracy':.9,'sampling':'All initial candidates; first completed human verdict per frozen version. Failed findings remain in the denominator.','versions':manifest})
    print(json.dumps({c:len(v) for c,v in grouped.items()}))

if __name__=='__main__':main()
