import {useEffect,useMemo,useState} from 'react';
import {geoNaturalEarth1,geoPath} from 'd3-geo';
import {feature} from 'topojson-client';
import atlas from 'world-atlas/countries-110m.json';
import {predictScenario} from './inference.mjs';
import type {Country,Evidence,Finding,Quant} from './types';

const colors:Record<string,string>={SE:'#3f8d77',US:'#6f79b6',SG:'#d38b4e'};
const numeric:Record<string,string>={'752':'SE','840':'US','702':'SG'};
const locations:Record<string,[number,number]>={SE:[16,63],US:[-101,39],SG:[103.8,1.35]};
const categories=['policy','legislation','funding','strategy','political statement'];
const fmt=(v:number,d=1)=>v.toFixed(d);
const modelNames:Record<string,string>={ridge:'Regularised regression',no_change:'No change',trend:'Previous five-year trend'};
const params=new URLSearchParams(location.search);
const limited=(key:string,min:number,max:number)=>Math.max(min,Math.min(max,Number(params.get(key))||0));
const world=(feature(atlas as any,(atlas as any).objects.countries) as any).features.filter((f:any)=>f.id!=='010');
function Arrow(){return <span aria-hidden="true">↗</span>}
function Tag({children,tone=''}:{children:React.ReactNode;tone?:string}){return <span className={`tag ${tone}`}>{children}</span>}

function WorldMap({countries,selected,onSelect}:{countries:Country[];selected:string;onSelect:(c:string)=>void}){
 const projection=geoNaturalEarth1().scale(146).translate([400,220]);const path=geoPath(projection);
 const [hint,setHint]=useState('Select Sweden, the United States or Singapore');
 return <section className="world panel" aria-label="Country coverage map">
  <div className="map-head"><div><span className="eyebrow">COUNTRY OBSERVATORY</span><h2>Where policy meets population.</h2></div><span className="map-count">03 <span>countries in scope</span></span></div>
  <svg className="world-svg" viewBox="0 0 800 415" role="img" aria-label="World map. Three countries are in scope; all others are unsearched.">
   <defs><radialGradient id="mapGlow"><stop stopColor="#527d65" stopOpacity=".3"/><stop offset="1" stopColor="#153d36" stopOpacity="0"/></radialGradient></defs><ellipse cx="390" cy="230" rx="350" ry="170" fill="url(#mapGlow)"/>
   {[100,180,260,340].map(y=><path key={y} d={`M25 ${y} H775`} stroke="#c0d4c7" strokeOpacity=".065"/>)}
   {world.map((f:any)=>{const id=numeric[String(f.id)];return <path key={f.id} d={path(f)||''} fill={id?selected===id?'#d5e5af':'#719b83':'#3a5a50'} stroke="#173d35" strokeWidth=".7" className={id?'map-country':''} onClick={()=>id?onSelect(id):setHint(`${f.properties.name}: unsearched; no policy conclusion`)} onMouseEnter={()=>setHint(id?`${countries.find(c=>c.id===id)?.name}: select to explore`:`${f.properties.name}: unsearched`)}><title>{f.properties.name}{id?' · in scope':' · unsearched'}</title></path>})}
   {countries.map(c=>{const [x,y]=projection(locations[c.id])!;const active=c.id===selected;return <g key={c.id} className="map-marker" tabIndex={0} role="button" aria-label={`Explore ${c.name}`} onClick={()=>onSelect(c.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(c.id)}}}>
    <circle cx={x} cy={y} r={active?15:10} fill="#d5e5af" opacity={active?.15:.08}/><circle cx={x} cy={y} r="4.5" fill={active?'#e1edbd':'#a6c6b0'} stroke="#143b32" strokeWidth="2"/>
    <text x={x+12} y={y+4} fill={active?'#edf4d8':'#c0d5c6'} fontSize="13" fontWeight="600">{c.name==='United States'?'United States':c.name}</text>
   </g>})}
  </svg><div className="map-foot"><span><i/> In scope <i className="muted-dot"/> Unsearched</span><span className="map-hint" aria-live="polite">{hint}</span></div>
 </section>
}

function LineChart({country,value,horizon,first}:{country:Country;value:number|null;horizon:number;first:number|null}){
 const w=720,h=270,pad={l:42,r:28,t:22,b:32};const minYear=1995,maxYear=country.origin+horizon;
 const values=country.history.map(p=>p.value);const low=Math.floor(Math.min(...values, value===null?country.latest:value-country.radius)-1),high=Math.ceil(Math.max(...values,value===null?country.latest:value+country.radius)+1);
 const x=(y:number)=>pad.l+(y-minYear)/(maxYear-minYear)*(w-pad.l-pad.r),y=(v:number)=>h-pad.b-(v-low)/(high-low)*(h-pad.t-pad.b);
 const line=country.history.map((p,i)=>`${i?'L':'M'}${x(p.year)},${y(p.value)}`).join(' ');
 const path=value===null?'':`M${x(country.origin)},${y(country.latest)} ${horizon===10&&first!==null?`L${x(country.origin+5)},${y(first)}`:''} L${x(maxYear)},${y(value)}`;
 return <svg className="line-chart" viewBox={`0 0 ${w} ${h}`} role="img" aria-label={`Observed life expectancy for ${country.name}, 1995 to ${country.origin}, with ${horizon}-year ${horizon===5?'forecast':'exploratory scenario'}`}>
  <rect x={x(country.origin)} y={pad.t} width={x(maxYear)-x(country.origin)} height={h-pad.t-pad.b} fill="#f2f4e9"/>
  {Array.from({length:5},(_,i)=>low+(high-low)*i/4).map(v=><g key={v}><line x1={pad.l} y1={y(v)} x2={w-pad.r} y2={y(v)} stroke="#e5e8e0" strokeDasharray="3 4"/><text x={pad.l-10} y={y(v)+4} textAnchor="end" className="chart-text">{v.toFixed(0)}</text></g>)}
  {[1995,2005,2015,country.origin,maxYear].map(v=><text key={v} x={x(v)} y={h-7} textAnchor="middle" className="chart-text">{v}</text>)}
  {value!==null&&horizon===5&&<path d={`M${x(country.origin)},${y(country.latest)} L${x(maxYear)},${y(value+country.radius)} L${x(maxYear)},${y(value-country.radius)} Z`} fill="#b8c79c" opacity=".3"/>}
  <path d={line} fill="none" stroke={colors[country.id]} strokeWidth="3" strokeLinejoin="round"/>
  <path d={path} fill="none" stroke="#456944" strokeWidth="2.5" strokeDasharray="6 5"/>
  <circle cx={x(country.origin)} cy={y(country.latest)} r="4" fill={colors[country.id]}/>
  {value!==null&&<circle cx={x(maxYear)} cy={y(value)} r="5" fill="#486c3f" stroke="white" strokeWidth="2"/>}
  <text x={x(country.origin)+9} y={16} fontSize="10" fill="#6b765b">{horizon===5?'FORECAST':'EXPLORATORY'}</text>
 </svg>
}

function Pyramid({country}:{country:Country}){
 const max=Math.max(1,...country.pyramid.flatMap(p=>[p.male,p.female]));
 return <section className="panel pyramid-panel"><div className="section-head"><div><span className="eyebrow">DEMOGRAPHIC CONTEXT</span><h3>The shape of a population.</h3></div><Tag>{country.pyramid_year}</Tag></div>
  <div className="pyramid-key"><span><i style={{background:colors[country.id]}}/>Male</span><span>Age</span><span><i style={{background:'#bbc9ac'}}/>Female</span></div>
  <div className="pyramid" role="img" aria-label={`Population age distribution for ${country.name}, percentage within each sex, ${country.pyramid_year}`}>
   {[...country.pyramid].reverse().map(p=><div className="pyramid-row" key={p.age}><div className="male"><span style={{width:`${p.male/max*100}%`,background:colors[country.id]}} title={`${p.male.toFixed(2)}% of male population`}/></div><small>{p.age}</small><div className="female"><span style={{width:`${p.female/max*100}%`}} title={`${p.female.toFixed(2)}% of female population`}/></div></div>)}
  </div><div className="pyramid-axis"><span>{max.toFixed(0)}%</span><span>0</span><span>{max.toFixed(0)}%</span></div>
  <p className="caption">Each side sums to 100% of its own sex. Observed age composition; no population projection.</p>
  <a className="source-link" href="https://data.worldbank.org/indicator/SP.POP.0004.MA.5Y" target="_blank" rel="noreferrer">World Bank / UN World Population Prospects <Arrow/></a>
 </section>
}

function EvidenceView({evidence,country}:{evidence:Evidence;country:Country}){
 const [category,setCategory]=useState('all');const [term,setTerm]=useState('');
 const findings=evidence.findings.filter(f=>f.country===country.id&&(category==='all'||f.classification===category)&&(`${f.claim} ${f.provenance.title}`).toLowerCase().includes(term.toLowerCase())).sort((a,b)=>b.source_date.localeCompare(a.source_date));
 const counts=evidence.countries[country.id];
 return <section className="evidence-view"><div className="section-head"><div><span className="eyebrow">THE SOURCE RECORD</span><h2>What has {country.name} put in place?</h2><p>Read the original. Check the date. Distinguish a proposal from an enacted rule.</p></div><div className="review-total"><b>{counts.approved}</b><span>human-approved findings</span></div></div>
  <div className="evidence-toolbar"><div className="filters"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>All types</button>{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><input aria-label="Search policy evidence" placeholder="Search the evidence…" value={term} onChange={e=>setTerm(e.target.value)}/></div>
  {counts.withheld>0&&<div className="notice"><span className="notice-icon">◷</span><div><b>{counts.withheld} candidate findings await human approval.</b><p>The public release withholds their claims. A search result or an automated extraction does not count as a verified finding.</p></div></div>}
  <div className="evidence-list">{findings.length?findings.map(f=><FindingCard key={f.id} finding={f}/>):<div className="empty-state"><span>⌕</span><h3>{counts.approved?'No findings match these filters.':'No human-approved findings in this release yet.'}</h3><p>{counts.approved?'Try another type or search term.':'This means review is incomplete. It does not mean the country has no relevant policy.'}</p></div>}</div>
  <div className="coverage-grid">{categories.map(c=>{const scope=evidence.coverage.find(r=>r.country===country.id&&r.classification===c);return <div key={c}><span>{c}</span><b>{scope?`${scope.query_count} logged ${scope.query_count===1?'query':'queries'}`:'Unsearched'}</b><small>{scope?.status==='retrieval_failed'?'Retrieval failed; coverage unresolved':scope?'Bounded discovery; not exhaustive':'No absence claim'}</small></div>})}</div>
 </section>
}
function FindingCard({finding:f}:{finding:Finding}){return <article className="finding"><div className="finding-date">{f.source_date.slice(0,4)}<small>{f.source_date.slice(5)||'Year precision'}</small></div><div className="finding-body"><div className="finding-tags"><Tag>{f.classification}</Tag><Tag tone="sage">{f.provenance.status.replaceAll('_',' ')}</Tag><span className="confidence">Source confidence: {f.confidence}</span></div><h3>{f.provenance.title}</h3><p>{f.claim}</p><details><summary>Inspect evidence & dates <span>+</span></summary><blockquote>{f.provenance.supporting_passage}</blockquote><dl><div><dt>Source publication</dt><dd>{f.provenance.publication_date}</dd></div><div><dt>Decision / launch</dt><dd>{f.provenance.decision_date||'Not established'}</dd></div><div><dt>Effective date</dt><dd>{f.provenance.effective_date||'Not established'}</dd></div></dl><p className="caption">{f.provenance.date_note}</p><small>Reviewed {f.review.reviewed_at.slice(0,10)} · Evidence version {f.review.version_hash.slice(0,12)}</small></details><a className="source-link" href={f.source_url} target="_blank" rel="noreferrer">{f.provenance.publisher} · {f.source_date} <Arrow/></a></div></article>}

function Methods({quant:q,evidence:e}:{quant:Quant;evidence:Evidence}){const v=q.evaluation;return <div className="methods"><div className="section-head"><div><span className="eyebrow">MEASURED, WITH LIMITS</span><h2>What the model earned. Where it failed.</h2><p>Predict five-year change in period life expectancy. Keep policy evidence separate from the fitted model.</p></div><Tag>Reproducible release</Tag></div>
 <div className="method-grid"><section className="panel"><h3>Historical forecast test</h3><p>Rolling origins 2014–2019, outcomes 2019–2024. Parameters and model choice selected before the test period.</p><table><thead><tr><th>Model</th><th>Error, years ↓</th><th>Interval coverage</th></tr></thead><tbody>{Object.entries(v.test).map(([name,m]:[string,any])=><tr key={name} className={name===q.model.selected?'selected-row':''}><td>{modelNames[name]}{name===q.model.selected&&<small>Selected on validation</small>}</td><td>{fmt(m.mae,2)}</td><td>{fmt(m.coverage*100,1)}%</td></tr>)}</tbody></table><p className="caption">{v.test.ridge.n.toLocaleString()} country-origin tests. Intervals targeted 90% using disjoint calibration countries at origin 2009. Actual coverage falls short; these are empirical error bands.</p></section>
 <section className="panel"><h3>Countries withheld from training</h3><p>Sweden, the US and Singapore were excluded from fitting, tuning and interval calibration. Six historical origins per country.</p><table><thead><tr><th>Country</th><th>Regression</th><th>No change</th><th>Trend</th></tr></thead><tbody>{q.countries.map(c=><tr key={c.id}><td>{c.name}</td>{['ridge','no_change','trend'].map(k=><td key={k}>{fmt(v.country_holdout[c.iso3][k].mae,2)}</td>)}</tr>)}</tbody></table><div className="inline-warning">The US regression loses to both baselines. Sweden’s trend baseline and Singapore’s no-change baseline also beat regression locally.</div></section></div>
 <div className="method-grid"><section className="panel"><h3>The model specification</h3><dl className="spec-list"><div><dt>Training data</dt><dd>{v.training_countries} countries / economies · {v.training_rows.toLocaleString()} rows</dd></div><div><dt>Outcome</dt><dd>Life expectancy at birth, total, years; five-year change</dd></div><div><dt>Inputs</dt><dd>Current life expectancy, previous five-year change, log GDP per capita, health spending and PM2.5</dd></div><div><dt>Time handling</dt><dd>GDP, spending and PM2.5 lagged one observation year. Training outcomes end no later than each test origin.</dd></div><div><dt>Missing data</dt><dd>Complete cases only. {v.missingness.excluded_missing_inputs.toLocaleString()} rows excluded. Tobacco and physician density excluded from the core model.</dd></div><div><dt>Estimator</dt><dd>Standardised ridge regression, α = {v.alpha}; scaling fitted only on training rows.</dd></div></dl></section>
 <section className="panel"><h3>Evidence review is a separate test</h3><div className="review-metrics"><strong>{e.benchmark.reviewed}<small> / {e.benchmark.sample_size}</small></strong><span>initial candidates reviewed by a person</span></div><p>{e.benchmark.accuracy===null?'Accuracy is not yet measured.':`${fmt(e.benchmark.accuracy*100,1)}% passed all four checks on their first completed review.`} The target is at least 90%, with the original sample frozen before correction.</p><p>The checks cover a resolving source, correct date, correct classification and a supported claim. Edited evidence invalidates an old approval.</p><p className="caption">{e.research.requests_used} / {e.research.request_cap} authorised provider requests used. {e.research.primary_documents} retrieved primary documents. All policy claims in the public app require a current human approval.</p></section></div>
 <section className="panel funding-lens"><div className="section-head"><div><span className="eyebrow">RESEARCH FUNDING LENS</span><h3>Who funds fundamental ageing science?</h3></div><Tag>Under investigation</Tag></div><p>We are testing a narrower comparison: public funding for research into the biological mechanisms of ageing. A national total needs the same scientific scope, financial stage and fiscal period in each country.</p><div className="funding-countries">{q.countries.map(c=><div key={c.id}><b>{c.name}</b><strong>Not established</strong><small>{e.funding?.candidate_programme_counts[c.id]?`${e.funding.candidate_programme_counts[c.id]} programme-level lead under review`:'National total unresolved'}</small></div>)}</div><p className="caption">A research programme, dementia budget or eldercare allocation is not automatically a fundamental-ageing total. No missing amount is treated as zero; these leads do not enter the forecast. Verified programme records appear under Policy evidence → Funding.</p></section>
 <section className="panel limits"><h3>Limits that affect a decision</h3><ul>{v.limitations.map((l:string)=><li key={l}>{l}</li>)}<li>Life expectancy at birth is neither healthy life expectancy nor remaining lifespan at age 65. Population pyramids are observed context.</li><li>No time-saving or adoption benefit has been measured with ministry analysts. The proposed pilot would test source verification and scenario interpretation.</li></ul></section>
 <section className="panel reconciliation"><h3>One series, with national-source differences</h3><p>The model consistently uses the World Bank's published series. National agencies can report different estimates: the US NCHS reports 79.0 years for 2024, compared with 78.89 in this WDI release; Singapore's Ministry of Health resident table reports 83.5, compared with 83.35 in WDI. These series are not silently substituted or averaged.</p><div className="reconciliation-links"><a href="https://www.cdc.gov/nchs/products/databriefs/db548.htm" target="_blank" rel="noreferrer">NCHS · January 2026 ↗</a><a href="https://www.moh.gov.sg/others/resources-and-statistics/population-and-vital-statistics/" target="_blank" rel="noreferrer">Singapore MOH · retrieved 11 Sep 2026 ↗</a><a href="https://www.scb.se/hitta-statistik/sverige-i-siffror/manniskorna-i-sverige/medellivslangd-i-sverige/" target="_blank" rel="noreferrer">Statistics Sweden · sex-specific tables ↗</a></div></section>
 <section className="panel"><h3>Data register & attribution</h3><p className="caption">{q.attribution}</p><div className="dataset-list">{q.datasets.filter(d=>!d.id.includes('5Y')).map(d=><details key={d.id}><summary>{d.title} <span>{d.licence} ↗</span></summary><p>{d.definition}</p><p>Units: {d.units} · API revision: {d.revision_date} · Retrieved: {d.retrieved_at.slice(0,10)}</p><a href={d.source_url} target="_blank" rel="noreferrer">Open exact API query <Arrow/></a></details>)}</div><p className="caption">Age / sex distributions: WDI’s SP.POP.*.5Y series, UN Population Division. Map: Natural Earth, public domain, packaged by world-atlas (ISC).</p></section>
 </div>}

export default function App(){
 const [data,setData]=useState<{q:Quant;e:Evidence}|null>(null);const [error,setError]=useState('');
 const [countryId,setCountryId]=useState(['SE','US','SG'].includes(params.get('country')||'')?params.get('country')!:'SE');
 const [tab,setTab]=useState(['outcomes','evidence','methods'].includes(params.get('tab')||'')?params.get('tab')!:'outcomes');
 const [horizon,setHorizon]=useState(params.get('horizon')==='10'?10:5);
 const [changes,setChanges]=useState({health:limited('health',-2,2),pollution:limited('pollution',-30,30),gdp:limited('gdp',-20,20)});
 const [shareMessage,setShareMessage]=useState('');
 useEffect(()=>{Promise.all([fetch('/release/quantitative.json'),fetch('/release/evidence.json')]).then(async([a,b])=>{if(!a.ok||!b.ok)throw Error('The release could not be loaded. Run the data and release commands, then refresh.');setData({q:await a.json(),e:await b.json()})}).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const p=new URLSearchParams({country:countryId,tab,horizon:String(horizon)});for(const[k,v]of Object.entries(changes))if(v)p.set(k,String(v));history.replaceState(null,'',`${location.pathname}?${p}`)},[countryId,tab,horizon,changes]);
 const country=data?.q.countries.find(c=>c.id===countryId);
 const scenario=useMemo(()=>data&&country?predictScenario(data.q.model,country,changes,horizon):null,[data,country,changes,horizon]);
 const baseline=useMemo(()=>data&&country?predictScenario(data.q.model,country,{},horizon):null,[data,country,horizon]);
 const select=(id:string)=>{setCountryId(id);setChanges({health:0,pollution:0,gdp:0})};
 const share=async()=>{try{await navigator.clipboard.writeText(location.href);setShareMessage('Scenario link copied')}catch{setShareMessage('Copy the URL from your address bar')}setTimeout(()=>setShareMessage(''),4000)};
 if(error)return <main className="loading"><h1>Release unavailable</h1><p>{error}</p><button onClick={()=>location.reload()}>Retry</button></main>;
 if(!data||!country||!scenario||!baseline)return <main className="loading"><div className="brand-mark">L</div><h1>Longview</h1><p>Loading the frozen evidence release…</p></main>;
 const {q,e}=data;const changed=Object.values(changes).some(Boolean);const delta=scenario.value!==null&&baseline.value!==null?scenario.value-baseline.value:null;
 return <><header className="site-header"><a href="/" className="brand"><span className="brand-mark"><svg viewBox="0 0 24 24"><path d="M5 5v14h15M9 14l5-7 6 3"/></svg></span>longview<span className="brand-divider"/><small>Policy & population health</small></a><nav aria-label="Main navigation"><button className={tab==='outcomes'?'current':''} onClick={()=>setTab('outcomes')}>Explore</button><button className={tab==='evidence'?'current':''} onClick={()=>setTab('evidence')}>Evidence</button><button className={tab==='methods'?'current':''} onClick={()=>setTab('methods')}>Method</button></nav><span className="prototype-badge"><i/> Research prototype</span></header>
 <main><div className="intro"><div><span className="eyebrow">FOR THE HEALTH MINISTRY ANALYST</span><h1>Take the long view.</h1><p>Compare national policies. Understand the population.<br className="mobile-break"/> Explore what the data can, and cannot, tell you.</p></div><div className="release-stamp"><span>OBSERVATIONS THROUGH 2024</span><b>Research snapshot · 11 Sep 2026</b><small>Public policy review: {e.benchmark.reviewed}/{e.benchmark.sample_size}</small></div></div>
 <button className={`verification-bar ${e.benchmark.complete?(e.benchmark.accuracy!==null&&e.benchmark.accuracy>=.9?'passed':'failed'):'pending'}`} onClick={()=>setTab('methods')} aria-label="Inspect the 90 percent human verification requirement"><div><span className="verification-icon">{e.benchmark.complete?(e.benchmark.accuracy!==null&&e.benchmark.accuracy>=.9?'✓':'!'):'◷'}</span><span><b>Evidence verification target ≥90%</b><small>Human checks of policy sources, dates, classifications and claims</small></span></div><div className="verification-progress"><span className="progress-track"><i style={{width:`${e.benchmark.sample_size?e.benchmark.reviewed/e.benchmark.sample_size*100:0}%`}}/></span><span>{e.benchmark.reviewed}/{e.benchmark.sample_size} reviewed</span></div><div className="verification-result"><b>{e.benchmark.accuracy===null?'Not yet measured':`${fmt(e.benchmark.accuracy*100,1)}% pass rate`}</b><small>{!e.benchmark.complete?'Pending complete human review':e.benchmark.accuracy!==null&&e.benchmark.accuracy>=.9?'Requirement passed':'Requirement not met'}</small></div><span className="verification-arrow">↗</span></button>
 <div className="overview"><WorldMap countries={q.countries} selected={countryId} onSelect={select}/><section className="country-spotlight panel"><div className="section-head"><span className="eyebrow">SELECTED COUNTRY</span><span className="country-code">{country.id}</span></div><h2>{country.name}</h2><p className="spotlight-sub">Life expectancy at birth · {country.origin}</p><div className="hero-number">{fmt(country.latest)}<span>years</span></div><div className="spotlight-rule"/><div className="spotlight-details"><div><span>Previous five-year change</span><b className={country.features.past_change>=0?'positive':''}>{country.features.past_change>=0?'+':''}{fmt(country.features.past_change,2)} years</b></div><div><span>Human-approved policies</span><b>{e.countries[country.id].approved}<small> / {e.countries[country.id].candidates} candidates</small></b></div></div><button className="text-button" onClick={()=>setTab('evidence')}>Explore the policy record <span>↗</span></button><a className="source-link" href={`https://data.worldbank.org/indicator/SP.DYN.LE00.IN?locations=${country.id}`} target="_blank" rel="noreferrer">World Bank · CC BY 4.0 <Arrow/></a></section></div>
 <div className="country-strip" aria-label="Compare countries">{q.countries.map(c=><button key={c.id} onClick={()=>select(c.id)} className={`country-card ${c.id===countryId?'selected':''}`} aria-pressed={c.id===countryId}><span className="country-symbol" style={{background:colors[c.id]}}>{c.id}</span><span className="country-card-label"><b>{c.name}</b><small>{e.countries[c.id].approved} approved policy findings</small></span><span className="country-card-value">{fmt(c.latest)}<small>years · {c.origin}</small></span><span className="card-arrow">↗</span></button>)}</div>
 <div className="workspace-tabs"><div role="tablist" aria-label="Analyst views">{[['outcomes','Outcomes & scenarios'],['evidence','Policy evidence'],['methods','Data & method']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}{id==='evidence'&&<span>{e.countries[country.id].approved}</span>}</button>)}</div><button className="print-button" onClick={()=>window.print()}>↓ Analyst brief</button></div>
 <div className="print-heading"><h2>{country.name}: analyst brief</h2><p>Release {q.release_id} / {e.release_id} · {horizon}-year horizon · Assumptions: health spending {changes.health} percentage points; PM2.5 {changes.pollution}%; GDP {changes.gdp}%.</p></div>
 {tab==='outcomes'&&<div className="outcomes"><div className="forecast-grid"><section className="panel forecast-chart"><div className="section-head"><div><span className="eyebrow">OBSERVATION → {horizon===5?'FORECAST':'SCENARIO'}</span><h2>How might the next {horizon} years look?</h2></div><Tag tone="sage">{country.name}</Tag></div><div className="chart-legend"><span><i style={{background:colors[country.id]}}/>Observed</span><span><i className="dashed"/>Conditional {horizon===5?'forecast':'scenario'}</span>{horizon===5&&<span><i className="band"/>Empirical error band</span>}</div><LineChart country={country} value={scenario.value} first={scenario.first} horizon={horizon}/><div className="chart-note"><span>World Bank published life-expectancy series, total population. Years.</span><a href="https://data.worldbank.org/indicator/SP.DYN.LE00.IN" target="_blank" rel="noreferrer">Source <Arrow/></a></div><div className="forecast-summary"><div><span>{country.origin+horizon} {horizon===5?'conditional forecast':'exploratory value'}</span><strong>{scenario.value===null?'Unavailable':fmt(scenario.value,2)}{scenario.value!==null&&<small> years</small>}</strong></div><div><span>{changed?'Difference from unchanged inputs':'Historical country test error'}</span><strong className="secondary">{changed?delta===null?'—':`${delta>=0?'+':''}${fmt(delta,2)}`:fmt(country.holdout_metrics.mae,2)}<small> years</small></strong></div></div><p className="caption">{horizon===5?`Error band: ±${fmt(country.radius,2)} years. It targeted 90% coverage but achieved ${fmt(q.evaluation.test[q.model.selected].coverage*100,1)}% in the wider historical test. It is not a guarantee for changed inputs.`:'This ten-year value applies the five-year model twice, holding the chosen covariates fixed. It has no ten-year validation or calibrated interval.'}</p>{country.id==='US'&&<div className="inline-warning"><b>US forecast reliability is limited.</b> Regression error was {fmt(q.evaluation.country_holdout.USA.ridge.mae,2)} years versus {fmt(q.evaluation.country_holdout.USA.no_change.mae,2)} for no change across six held-out origins.</div>}</section>
 <section className="panel scenario-panel"><div className="section-head"><div><span className="eyebrow">CHANGE AN ASSUMPTION</span><h3>A scenario, made explicit.</h3></div><button className="reset" onClick={()=>{setChanges({health:0,pollution:0,gdp:0});setHorizon(5)}}>Reset ↺</button></div><div className="horizon" aria-label="Scenario horizon"><button className={horizon===5?'active':''} onClick={()=>setHorizon(5)}>5 years<small>Historically tested</small></button><button className={horizon===10?'active':''} onClick={()=>setHorizon(10)}>10 years<small>Exploratory</small></button></div><p className="scenario-intro">Set alternative {country.input_year} indicator values. These are your assumptions, not estimated effects of a policy.</p>
 {[{key:'health',label:'Health expenditure',unit:'pp of GDP',min:-2,max:2,step:.1,context:`Observed: ${fmt(country.features.health_spending)}% of GDP`},{key:'pollution',label:'PM2.5 exposure',unit:'%',min:-30,max:30,step:1,context:`Observed: ${fmt(country.features.pm25)} µg/m³`},{key:'gdp',label:'GDP per capita',unit:'%',min:-20,max:20,step:1,context:`Observed: ${Math.round(Math.exp(country.features.log_gdp)).toLocaleString()} PPP dollars`}].map(s=><div className="slider-group" key={s.key}><label htmlFor={s.key}>{s.label}<output>{changes[s.key as keyof typeof changes]>0?'+':''}{changes[s.key as keyof typeof changes]} <small>{s.unit}</small></output></label><input id={s.key} type="range" min={s.min} max={s.max} step={s.step} value={changes[s.key as keyof typeof changes]} onChange={e=>setChanges({...changes,[s.key]:Number(e.target.value)})}/><span className="slider-context">{s.context} · {country.input_year}</span></div>)}
 {!scenario.available&&<div className="inline-warning" role="status">Outside the training range: {scenario.outside.join(', ')}. No numeric scenario is shown.</div>}<div className="scenario-warning"><span>ⓘ</span><p>Associations are not causes. Spending more does not automatically create the displayed change in life expectancy.</p></div><button className="primary-button" onClick={share}>Share this scenario <Arrow/></button><div className="share-status" role="status">{shareMessage||`Base year ${country.origin} · Inputs ${country.input_year}`}</div></section></div>
 <div className="context-grid"><Pyramid country={country}/><section className="panel context-panel"><span className="eyebrow">BEFORE YOU MAKE A RECOMMENDATION</span><h2>A forecast is one<br/>part of the brief.</h2><p>The model uses numerical indicators from a wider country panel. The policy record answers a separate question: what was proposed, funded or put into place?</p><div className="context-step"><span>01</span><div><h4>Trace the policy</h4><p>Inspect the original source and the event’s legal or administrative status.</p></div></div><div className="context-step"><span>02</span><div><h4>Stress-test the assumption</h4><p>Change a numerical input. Keep its link to the policy as an explicit, untested assumption.</p></div></div><div className="context-step"><span>03</span><div><h4>Carry the uncertainty forward</h4><p>Include baseline errors, data lag and country-specific failures in the analyst brief.</p></div></div><button className="text-button" onClick={()=>setTab('methods')}>Inspect the evaluation <Arrow/></button></section></div></div>}
 {tab==='evidence'&&<EvidenceView evidence={e} country={country}/>}{tab==='methods'&&<Methods quant={q} evidence={e}/>}
 <footer><div><a className="brand" href="/">longview</a><span>Built for the Stockholm AI × Longevity Hackathon · 2026</span><nav className="delivery-links" aria-label="Demo Day downloads"><a href="/downloads/longview-three-slides.pdf" target="_blank" rel="noreferrer">3-slide pitch · PDF ↗</a><a href="/downloads/longview-three-slides.pptx" download>Editable slides ↓</a><a href="/downloads/longview-demo.webm" target="_blank" rel="noreferrer">Watch the demo ↗</a><a href="/downloads/longview-offline.zip" download>Offline app ↓</a></nav></div><p>Public aggregate data. Research prototype. No clinical or causal claims.<br/><span>Evidence {e.release_id} · Model {q.release_id} · No live research endpoint</span></p></footer>
 </main></>
}
